# Generated by Django 5.2.12 on 2026-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128)),
                ('user_message', models.TextField()),
                ('therapist_report', models.TextField()),
                ('tool_used', models.CharField(blank=True, max_length=128, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
