# Generated by Django 5.2.12 on 2026-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreport',
            name='status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed')], default='unreviewed', max_length=32),
        ),
    ]
