# Generated by Django 5.2.12 on 2026-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat', '0002_chatsession_chattherapistassignment_delete_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='anonymous_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_stage',
            field=models.CharField(choices=[('emotional_check', 'Emotional Check'), ('lifestyle_sleep', 'Lifestyle + Sleep'), ('social_work', 'Social + Work'), ('deep_mental_state', 'Deep Mental State'), ('risk_assessment', 'Risk Assessment'), ('analysis', 'Analysis')], db_index=True, default='emotional_check', max_length=40),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='final_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='severity_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='severity_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
