# Generated by Django 5.2.12 on 2026-04-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat', '0003_chatsession_anonymous_user_id_chatsession_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='report_visible_to_therapist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='report_visible_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
