# Generated by Django 5.2.12 on 2026-03-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='session_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='room_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
