# Generated by Django 5.2.12 on 2026-03-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_demo_accounts'),
        ('therapy_sessions', '0004_therapysession_feedback_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.therapistprofile')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('therapist', 'start_time', 'end_time')},
            },
        ),
    ]
