# Generated by Django 5.2.12 on 2026-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0007_alter_therapysession_status_and_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
