# Generated by Django 5.2.12 on 2026-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0008_session_google_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='meeting_link',
            field=models.URLField(),
        ),
    ]
