# Generated by Django 5.2.12 on 2026-04-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0010_alter_session_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
