# Generated by Django 5.2.12 on 2026-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_mental_health_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='university_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
