# Generated by Django 5.2.12 on 2026-04-19 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_demo_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
