# Generated by Django 5.2.12 on 2026-03-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0003_screeningsession_screening_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningsession',
            name='chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='screeningsession',
            name='chat_turns',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
